# Generated by Django 5.1.4 on 2025-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.avif', upload_to='profile_pics'),
        ),
    ]
